title: "[Plan] YYYY-MM-DD  "
labels: ["planning"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🗂️ 기획 회의

  - type: textarea
    id: discussion
    attributes:
      label: 논의
      description: 회의에서 논의한 내용을 번호로 작성해주세요
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: decisions
    attributes:
      label: 결정사항
      description: 최종적으로 결정된 사항을 번호로 작성해주세요
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: next-action
    attributes:
      label: 다음 액션
      placeholder: 회의 이후 각자 해야 할 작업을 작성해주세요
